language: node_js

node_js:
  - "iojs"

# Not yet!
#services:
  #- mongodb

script:
    - ./node_modules/.bin/jscs app/
    - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec tests/unit/**/*.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    # Not yet!
    #- ./node_modules/.bin/mocha test/integration/*.js
